FROM registry.access.redhat.com/ubi8/python-38
WORKDIR /app
COPY . /app
#RUN pip3 install -r requirements.txt --no-cache-dir
# USER root
# RUN mkdir custom
# RUN cd custom
# COPY . /app/custom
# RUN touch extension.txt